on:
  push:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: hello
        run: echo "Hello World"
      - name: second step
        run: echo "Hello"

  test:
    name: test python
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install
        run: pip install .[test]
      - name: Run
        run: pytest -vv